"""Build the readable dossier and evidence index from canonical docs and source catalog.
Public numeric samples are preserved in dist/data; this command performs no network fetch.
"""
from pathlib import Path
import json,hashlib
ROOT=Path(__file__).resolve().parent.parent
SITE=ROOT/'presentation-site'; DIST=SITE/'dist'
c=json.loads((SITE/'content/research-and-media.json').read_text())
lines=['# 11 · Khảo sát phương pháp học từ dữ liệu đa nguồn','', '_Catalog gốc kiểm 02/10/2026; DataMIL bổ sung, kiểm 05/10/2026. Đây là kết quả/thiết kế của tác giả; không là kết quả của đội. P0/P1/P2 là ưu tiên MVP, không xếp hạng chất lượng công trình._','', '## Kết luận cho thiết kế','', 'Human/video mở prior và coverage; bridge cần chọn theo tín hiệu. Synthetic có ba loại supervision khác nhau. Dữ liệu robot thật giữ vai trò học điều khiển, hiệu chuẩn, contact/recovery và đánh giá độc lập. FluxVLA có sẵn nhiều năng lực platform/SDG/HITL; đóng góp của đội phải đo ở recipe, binding, mixture và hiệu quả theo task, không chỉ wrapper.','', 'Không đối chiếu success percentages giữa các paper như leaderboard: task, robot, splits và protocol khác nhau. HumanEgo có cấu hình robot-data-free; không nói mọi human-to-robot learning đều bắt buộc teleop. Thiết kế này chủ động dùng real-robot anchors.','']
for m in c['methods']:
 lines += [f"## {m['name']} · {m['year']}",'',f"Nguồn: [{m['name']}]({m['url']}).",'',f"**Input:** {m['input']}",f"**Cơ chế:** {m['mechanism']}",f"**Tận dụng:** {m['reuse']}",f"**Giới hạn:** {m['limit']}",f"**Ưu tiên:** {m['priority']}",'']
lines+=['## Chọn đường trong ba tháng','','P0: FluxVLA/GR00T N1.5/GR1 robot baseline và E4 T/F/A từ parent R0. P1: human/video heads, source-drop, compute control và Cosmos-vs-basic sau gate. P2: physics/world-model generation, full-body geometry và WAM. Không train foundation models từ đầu.','', 'MVP chọn robot baseline trên FluxVLA/GR00T N1.5/GR1 trước; auxiliary stage/order/wrist heads có gate signals/rights/E0 riêng. Bốn nguồn là catalog, không mandatory recipe. Core 15 runs: 6 R0 +9 T/F/A, extension tối đa 12. DataMIL là prior art về selection; selection/QA compute và engineer hours phải tính vào total cost.','', '[Learning Core](04-learning-core.md) · [Protocol](06-validation-and-roadmap.md) · [Mẫu dữ liệu](12-public-data-examples.md).']
(ROOT/'docs/11-method-survey.md').write_text('\n'.join(lines)+'\n')
g1=json.loads((DIST/'data/g1-episode-0.json').read_text());h=json.loads((DIST/'data/humanego-hands.json').read_text())
lines=['# 12 · Public data examples và media provenance','','_Website đã có numerical previews, Figure 1 FluxVLA lưu cùng hồ sơ và remote media; chưa có dataset của đội hoặc training result. Clip GR1 episode 0 (18,8 giây) và ảnh xem trước thật lưu cùng website/ZIP để phát ổn định; media còn lại tải từ nguồn tác giả._','','## Mẫu robot thật · Unitree G1/Dex3','','Dataset: [G1_Dex3_ToastedBread_Dataset]('+c['g1']+'). Repository revision quan sát: `'+c['g1Revision']+'`.', '',f"Metadata hiện tại: **{g1['format']}**, 30fps, episode 0 có **620 frames** và segment video 0–20,6667 giây trong file ghép nhiều episodes. Mỗi frame có 28 `observation.state` và 28 `action` values; khớp tay và bàn tay được ghi tên. Không tự nhận force/contact/outcome labels không có trong mẫu.",'','Nguồn số: [Hugging Face Rows API]('+g1['provenance']['numericSource']+'). API lấy current revision, không có pin SHA trong request; video/metadata URLs pin SHA. Đã kiểm episode index, frame order, timestamp, chiều tensor; chưa claim bitwise equality với pinned parquet.','', 'Giá trị state và action khác nhau là sự khác nhau giữa observation và action target của dataset; độ lệch không tự chứng minh controller lỗi. Card có ví dụ v2, metadata hiện v3.0; integration phải pin loader thích hợp. Dataset card mô tả current state và next action; collector/controller timing chưa kiểm nên inspector không tự gọi action là command đã gửi. Dataset card ghi Apache-2.0, kiểm riêng quyền assets/downstream trước deployment.','','## Mẫu human thật · HumanEgo','','Dataset: [Leo-TX/HumanEgo]('+c['human']+'). Revision: `'+c['humanRevision']+'`. Recording `serve_bread/aria/mps_serve_bread_000_vrs`, 1002 tracking rows.','', 'CSV `hand_tracking/hand_tracking_results.csv`; camera config `preprocess/aria_cam_rgb_config.json`. Preview giữ timestamp, confidence và wrist translations. Raw row 0: right confidence=-1, raw wrist=[0,0,0], normalized wrist=null. Đây là ví dụ thực về missing tracking và validity mask, không giả bàn tay ở tọa độ gốc.','', 'CSV timestamps ở microseconds; camera config first_ts ở nanoseconds. Visualization và raw tracking là cùng recording nhưng frontend không giả frame-paired alignment chưa kiểm. Không coi human wrist là robot joint action. Data CC BY-NC 4.0 và code PolyForm Noncommercial khác nhau; đây là public research reference.','','## Media credits','','Mỗi asset có evidence type, caption và source page. Các samples không phải paired demonstrations của task DENSO. Task gắp chi tiết vào khay là ví dụ đề xuất, chưa dữ liệu thực của đội.','']
for key,m in c['media'].items():
 lines += [f"### {m['title']}",'',f"{m['kind']}. {m['caption']}",'',f"[Nguồn chính thức]({m['source']}) · [{'Hình lưu cùng hồ sơ' if m['url'].startswith('assets/') else 'Remote asset'}]({m['url']})",'']
 if m.get('playbackUrl'):
  lines += [f"Clip xem trong website: `{m['playbackUrl']}`; poster: `{m['poster']}`. Nguồn gốc NVIDIA/RoboCasa qua FluxVLA subset, [CC BY-NC 4.0]({m['license']['url']}); chỉ minh họa hồ sơ nghiên cứu/idea. MP4 được remux faststart, không đổi frames; poster trích tại t=0. Không phải kết quả của đội.",'',f"Provenance: `{json.dumps(m['provenance'],ensure_ascii=False)}`",'']
lines+=['## Integrity và phân phối','','Numerical samples, Figure 1 FluxVLA và clip GR1 đọc được offline; các video/ảnh remote khác cần internet và codec browser. Source hash dưới đây giúp nhận diện preview đã đóng gói, không thay hash raw dataset.','']
for p in sorted((DIST/'data').glob('*.json')):
 if p.name in ['g1-episode-0.json','humanego-hands.json','libero-preview.json','gr1-preview.json']:lines.append(f"- `{p.name}` · SHA-256 `{hashlib.sha256(p.read_bytes()).hexdigest()}`")
lines+=['','[Data Core](03-data-core.md) · [SOP](10-data-collection-sop.md) · [Khảo sát](11-method-survey.md).']
lines+=['','## Mẫu LeRobotDataset v3 · LIBERO simulation demonstrations','','[lerobot/libero](https://huggingface.co/datasets/lerobot/libero). Dataset revision `'+c['liberoRevision']+'`. Panda simulation demonstrations, không real-humanoid teleop. Metadata: v3.0, 1693 episodes, 273465 frames, 40 tasks, 10fps; 2 cameras 256×256, state float32[8], action float32[7].','', 'Instruction task 0 trong tasks.parquet: put the white mug on the left plate and put the yellow and white mug on the right plate. Episode 0 có 214 frames, segment hai camera 0–21,4s. Preview `libero-preview.json` giữ 6 rows đầu episode 0 từ Rows API ngày 02/10/2026, không toàn episode. Numeric API đọc current revision, chưa bitwise đối chiếu pinned parquet. Metadata URL pin SHA; không tự gán tên/units các dimensions chỉ ghi generic state/actions.','', 'LeRobot v3: meta/info.json, meta/tasks.parquet, meta/episodes/chunk-000/file-000.parquet, data/chunk-000/file-000.parquet và videos/{video_key}/chunk-000/file-000.mp4. Episode metadata chỉ vị trí episode trong các file ghép; không giả mỗi episode một MP4. [Đặc tả chính thức](https://huggingface.co/docs/lerobot/main/en/lerobot-dataset-v3). Dataset viewer/video là của tác giả; không cặp human–robot đã align với G1/HumanEgo.']
lines+=['','## Humanoid benchmark · RoboCasa GR1 và FluxVLA subset','','[Benchmark chính thức](https://github.com/robocasa/robocasa-gr1-tabletop-tasks): 24 tabletop tasks. [NVIDIA teleop-sim](https://huggingface.co/datasets/nvidia/PhysicalAI-Robotics-GR00T-Teleop-Sim) công bố 1000 demos/task, CC BY-NC 4.0. [FluxVLA subset]('+c['gr1']+') có 24 task folders và 720 episode Parquets (30/task), kiểm repository API ngày 03/10/2026. HumanoidBench là whole-body RL benchmark, không tự có expert LeRobot demonstrations như LIBERO.','', 'Ví dụ pinned subset PnPBottleToCabinetClose: LeRobot v2.1, robot GR1ArmsAndWaistFourierHands, 20fps, ego camera 256×256, state/action float64[29]. Folder metadata: 30 episodes, 10772 frames. Episode 0: 376 frames. JSON giữ 6 rows đầu trích trực tiếp từ pinned Parquet, URL và SHA-256 của raw Parquet; không Rows API current mismatch.','', 'Instruction mô tả đưa chai vào tủ rồi đóng cửa; waist unlocked, khác fixed-torso task khay. metadata splits.train=0:100 chưa khớp subset 30 episodes; tasks indices 0 và 1 lặp instruction. Preview giữ nguyên, tra task index của row, không gọi duplicate labels là hai task khác nhau. Loader/binding/normalization phải kiểm theo actual episode list và selected model config.','', 'Card FluxVLAData Apache-2.0 không tự thay quyền gốc NVIDIA CC BY-NC 4.0 cho assets/data dẫn xuất. Đây là public research preview; chưa tự kết luận đủ quyền commercial. Số chiều 29 của subset không áp cho mọi release GR1 hay robot G1.']
(ROOT/'docs/12-public-data-examples.md').write_text('\n'.join(lines)+'\n')
prefix='/* Generated by build-content.py from the source catalog. */\n'
for name,key in [('RESEARCH','methods'),('MEDIA','media'),('HF_G1','g1'),('HF_HUMAN','human'),('G1_REV','g1Revision'),('HUMAN_REV','humanRevision'),('HF_LIBERO','libero'),('LIBERO_REV','liberoRevision'),('HF_GR1','gr1'),('GR1_REV','gr1Revision')]:prefix+=f'const {name} = '+json.dumps(c[key],ensure_ascii=False)+';\n'
cost=json.loads((SITE/'content/industrial-cost-model.json').read_text())
prefix+='const INDUSTRIAL_COST = '+json.dumps(cost,ensure_ascii=False)+';\n'
(DIST/'data/industrial-cost-model.json').write_text(json.dumps(cost,ensure_ascii=False,indent=2)+'\n')
pilot=json.loads((SITE/'content/pilot-budget.json').read_text())
prefix+='const PILOT_BUDGET = '+json.dumps(pilot,ensure_ascii=False)+';\n'
(DIST/'data/pilot-budget.json').write_text(json.dumps(pilot,ensure_ascii=False,indent=2)+'\n')
(DIST/'evidence.js').write_text(prefix)
docs=[]
for p in sorted((ROOT/'docs').glob('[0-9][0-9]-*.md')):
 docs.append({'path':str(p.relative_to(ROOT)),'title':p.read_text().splitlines()[0].removeprefix('# '),'markdown':p.read_text()})
for p in [ROOT/'docs/reviews/idea-review.md',ROOT/'deliverables/Human-first-Humanoid-Pitch.md']:
 docs.append({'path':str(p.relative_to(ROOT)),'title':p.read_text().splitlines()[0].removeprefix('# '),'markdown':p.read_text()})
(DIST/'dossier.js').write_text('const DOSSIER = '+json.dumps(docs,ensure_ascii=False)+';\nconst SCORE_MODEL = '+(ROOT/'docs/reviews/idea-score.json').read_text()+';\n')
manifest={'generated':'2026-10-05','catalogChecked':'2026-10-02','media':c['media'],'methods':c['methods'],'samples':[{'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'sampleChecked':json.loads(p.read_text()).get('checked','2026-10-02')} for p in (DIST/'data').glob('*.json') if p.name in ['g1-episode-0.json','humanego-hands.json','libero-preview.json','gr1-preview.json']]}
(DIST/'data/source-manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
print('Built',len(c['methods']),'research entries,',len(c['media']),'media credits,',len(docs),'readable documents.')
